version: '3.2'
services:
  api:
    build: ./api
    # command: npm run start:dev
    volumes:
      - './api:/srv/api'
      - '/srv/api/node_modules'
    ports:
      - '${NODE_API_PORT}:3000' # Expose ports without publishing them to the host machine
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db/:/data/db
    ports:
      - ${MONGO_PORT}:27017 # expose ports - HOST:CONTAINER
